### ISSUE TITLE
README.md: typo in sandbox URL

### ISSUE THREAD

**Issue by okft** [maxmind/minfraud-api-node#1340]
Hi,

I noticed there is a typo in your README.md file and more precisely in sandbox URL:
```js
const client = new minFraud.Client("1234", "LICENSEKEY", 3000, 'sandbox.minfraud.com');
```
should be
 ```js
const client = new minFraud.Client("1234", "LICENSEKEY", 3000, 'sandbox.maxmind.com');
```
at least according to [MAXMIND Sandbox Environment page](https://dev.maxmind.com/minfraud/sandbox-environment). 

Let me know if I have to create a merge request or if you can fix it yourselves.

Best regards,

**Comment by oschwald** [comment]
Thanks! This was fixed in #1341.
