### ISSUE TITLE
Can't require minfraud-api-node

### ISSUE THREAD

**Issue by GuetaHen** [maxmind/minfraud-api-node#21]
When trying to run "const minFraud = require('@maxmind/minfraud-api-node');" i get "uncaughtException: Cannot find module '@maxmind/minfraud-api-node'".
I think the problem in the package.json on "main": "dist/index.js", the path to the file doesn't exist.

**Comment by kevcenteno** [comment]
@GuetaHen Fix has been released in version 1.0.0
