### ISSUE TITLE
Disposition API

### ISSUE THREAD

**Issue by 0xGREG** [maxmind/minfraud-api-node#440]
Is it possible to use the disposition API?

I'd like to check if a transaction was approved or denied.

Thanks!

**Comment by kevcenteno** [comment]
@0xGREG The disposition API isn't included in this library, and we don't have any immediate plans to include it.  We are open to pull requests though :)

In the meantime, you can use the [REST API](https://dev.maxmind.com/minfraud/dispositions-api/) directly.
